package com.example.entity;\n\npublic class User {}
// incremental change 1
// incremental change 6
// incremental change 11
// incremental change 13
// incremental change 21
// incremental change 24
// incremental change 38
// incremental change 47
// incremental change 53
// incremental change 54
// incremental change 69
// incremental change 72
// incremental change 80
// incremental change 83
// incremental change 84
// incremental change 90
// incremental change 92
// incremental change 100
// incremental change 101
// incremental change 112
// incremental change 113
// incremental change 121
// incremental change 123
// incremental change 137
// incremental change 4
// incremental change 15
// incremental change 21
// incremental change 26
// incremental change 29
// incremental change 32
// incremental change 40
// incremental change 47
// incremental change 49
