package com.example.exception;\n\npublic class GlobalExceptionHandler {}
// incremental change 5
// incremental change 7
// incremental change 8
// incremental change 20
// incremental change 22
// incremental change 27
// incremental change 35
// incremental change 45
// incremental change 46
// incremental change 55
// incremental change 57
// incremental change 60
// incremental change 66
// incremental change 67
// incremental change 71
// incremental change 73
// incremental change 74
// incremental change 76
// incremental change 93
// incremental change 98
// incremental change 105
// incremental change 106
// incremental change 107
// incremental change 108
// incremental change 109
// incremental change 114
// incremental change 131
// incremental change 135
// incremental change 136
// incremental change 144
// incremental change 146
// incremental change 1
// incremental change 10
// incremental change 13
// incremental change 18
// incremental change 24
// incremental change 25
// incremental change 27
// incremental change 41
// incremental change 50
// incremental change 51
// incremental change 57
// incremental change 58
// incremental change 64
// incremental change 67
// incremental change 70
// incremental change 76
// incremental change 78
// incremental change 79
// incremental change 83
// incremental change 93
// incremental change 100
// incremental change 102
// incremental change 113
// incremental change 115
// incremental change 116
// incremental change 122
// incremental change 129
// incremental change 130
// incremental change 133
// incremental change 138
// incremental change 141
// incremental change 2
// incremental change 3
// incremental change 4
// incremental change 6
// incremental change 12
// incremental change 25
