package com.example.exception;\n\npublic class GlobalExceptionHandler {}
// incremental change 5
// incremental change 7
// incremental change 8
// incremental change 20
// incremental change 22
// incremental change 27
// incremental change 35
// incremental change 45
// incremental change 46
// incremental change 55
// incremental change 57
// incremental change 60
// incremental change 66
// incremental change 67
// incremental change 71
// incremental change 73
// incremental change 74
// incremental change 76
// incremental change 93
// incremental change 98
// incremental change 105
// incremental change 106
